marketing_tool/urls.py
from django.contrib import admin
from django.urls import path, include  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('marketing_tool_lead_manager_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls'))
]


marketing_tool_lead_manager_app/urls.py
#--- Marketing Tool - Imported Packages List ----

#------Django Internal Packages-----
from django.urls import include, path,re_path
from django.contrib.auth import views as auth_views
#<------Django Internal Packages-----

#------ Marketing Tool Importing Project Files -----
#Marketing Tool - Our Application Views
from marketing_tool_lead_manager_app import views

#</--- Marketing Tool Importing Project Files ----

app_name = 'marketing_tool_lead_manager_app'




#--- Marketing Tool Data Management URL List ----
urlpatterns = [

# ------ Marketing Tool Index Form URLs -----

#Marketing Tool - Index Form
path("", views.survey_form, name="home"),

path('sentry-debug/', views.survey_form),
#Marketing Tool - Survey  Form
#path("survey_form", views.survey_form, name="survey_form"),

#Marketing Tool - Survey Form Submit
path("home_form_submit", views.home_form_submit, name="home_form_submit"),

#path("home_form_submit", views.home_form_submit, name="home_form_submit"),

#</------ Marketing Tool Index Form URLs -----

#------ Marketing Tool All Leads Urls -----

#Marketing Tool - Summary Page URL
#path("summary", views.summary, name="summary"),

#Marketing Tool - All Leads URL
path("leads", views.lead_zing_grid_list, name="lead_zing_grid_list"),

#</------ Marketing Tool All Leads Urls -----


#------ Marketing Tool Leads by City Urls -----

#Marketing Tool - Leads by City URL
path("leads/mumbai", views.lead_zing_grid_list_mumbai, name="lead_zing_grid_list_mumbai"),

#</------ Marketing Tool All Leads Urls -----

#<------ Marketing Tool All Routes Urls -----

#Marketing Tool - All Routes List
path("routes", views.all_routes, name="routes"),

#Marketing Tool - All Routes Details
path("routes/details", views.routes_details, name="routes_details"),

#Marketing Tool - Leads Details based on Location From, Location To, Login Time and Logout Time (Zinggrid Table)
path('leads/details/<int:location_from>/<int:location_to>/<int:login_time>/<int:logout_time>/',views.leads_locationfrom_locationto_logintime_logouttime,name='leads_locationfrom_locationto_logintime_logouttime'),

#Marketing Tool - Leads Details based on Location From, Location To, Login Time and Logout Time (Data Table)
path('leads/detail/<int:location_from>/<int:location_to>/<int:login_time>/<int:logout_time>/',views.leads_locationfrom_locationto_logintime_logouttime_dt,name='leads_locationfrom_locationto_logintime_logouttime_dt'),



#</------ Marketing Tool All Routes Urls -----

#<------ Marketing Tool City Routes Urls -----

#Marketing Tool - Mumbai Routes List
path("routes/city", views.leads_routes, name="leads_routes"),

#Marketing Tool - Mumbai Routes Details
path("routes/city/details", views.city_routes_details, name="city_routes_details"),


#</------ Marketing Tool City Routes Urls -----

#<------ Marketing Tool Location From Urls -----
#Marketing Tool - Location From
path("location_from", views.location_from, name="location_from"),

#</------ Marketing Tool Location From Urls -----

#<------ Marketing Tool Location To Urls -----
#Marketing Tool - Location To
path("location_to", views.location_to, name="location_to"),

#<------ Marketing Tool Location To Urls -----

#<------ Marketing Tool Login Time Urls -----
#Marketing Tool - Login Time
path("login_time", views.login_time, name="login_time"),

#</------ Marketing Tool Login Time Urls -----

#<------ Marketing Tool Logout Time Urls -----

#Marketing Tool - Logout Time
path("logout_time", views.logout_time, name="logout_time"),

#</------ Marketing Tool Logout Time Urls -----


#<------ Marketing Tool Portal Users Urls -----

#Marketing Tool - User List
path("users", views.users, name="users"),

#</------ Marketing Tool Portal Users Urls -----


#<------ Marketing Tool User Authentication Urls -----

#Marketing Tool - Sign In
path("Login", views.Login, name="Login"),


 #Marketing Tool - Sign Up
path("register", views.register, name="register"),

#Marketing Tool - Sign Up
path('sign_out/', views.user_sign_out, name = 'sign_out'),

#Marketing Tool - Forget Password
#path("forgetpassword" , views.forgetpassword, name="forgetpassword"),

#</------ Marketing Tool User Authentication Urls -----


#<------ Marketing Tool BS Modal Urls -----

#Marketing Tool - read url
path('read/<int:pk>', views.LeadReadView.as_view(), name='read_lead'),

#Marketing Tool - update url
path('update/<int:pk>', views.LeadUpdateView.as_view(), name='update_lead'),

#Marketing Tool - delete url
path('delete/<int:pk>', views.LeadDeleteView.as_view(), name='delete_lead'),

#Marketing Tool - location update
path('update/location/<int:pk>', views.LocationUpdateView.as_view(), name='update_location'),


#</------ Marketing Tool BS Modal Urls -----


#<------ Marketing Tool Rest API Urls -----

path('leads_api/', views.Leads_API.as_view(), name='leads_api2_list'),

path('leads_mumbai_api/', views.Leads_Mumbai_API.as_view(), name='Leads_Mumbai_API'),

path('routes/list', views.routes_list, name='routes_list'),

#</------ Marketing Tool Experiment URLS-----

path('routes/experiment', views.all_routes_experiment, name='all_routes_experiment'),

#</------ Marketing Tool :ead_status_details_url-----

#path('leads_status_details/<int:pk>', views.leads_status_details.as_view(), name='leads_status_details'),


#<------ Marketing Tool Zing Grid Test -----
#path('lead_zing_grid_list',views.lead_zing_grid_list,name='lead_zing_grid_list'),

#path('lead_zing_grid_list_mumbai',views.lead_zing_grid_list_mumbai,name='lead_zing_grid_list_mumbai'),

#path('routes_zing_grid_list',views.routes_zing_grid_list,name='routes_zing_grid_list'),	

#path('leads_api/details/<int:location_from>/<int:location_to>/<int:login_time>/<int:logout_time>/', views.leads_api_Details.as_view()),



#<------ Marketing Tool B2B Company Leads Urls -----

#Marketing Tool - Company Leads base 
path("company_lead_base", views.company_lead_base, name="company_lead_form"),


#Marketing Tool - Company Leads Form 
path("company/form", views.company_lead_form, name="company_lead_form"),

#Marketing Tool - Company Leads Data
path("company/leads", views.company_lead_data, name="company_lead_data"),

#Marketing Tool - Company Leads Report 
path("company/reports", views.company_lead_report, name="company_lead_report"),

#Marketing Tool - Company Leads Report 
path("company_lead_form_submit", views.company_lead_form_submit, name="company_lead_form_submit"),
#</------ Marketing Tool B2B Company Leads Urls -----

path("view_leads/<int:pk>", views.view_leads, name="view_leads"),

path("add_new_lead_status/<int:pk>",views.add_new_lead_status, name='add_new_lead_status'),

path('updatelead/<int:pk>',views.updatelead.as_view(),name='updatelead'),

path('deletelead/<int:pk>',views.deletelead.as_view(),name='deletelead'),

path('update_login_time/<int:pk>', views.update_login_time.as_view(), name='update_login_time'),

path('update_logout_time/<int:pk>', views.update_logout_time.as_view(), name='update_logout_time'),

path('update_login_time/<int:pk>', views.update_login_time.as_view(), name='update_login_time'),

path('delete_login_time/<int:pk>', views.delete_login_time.as_view(), name='delete_login_time'),

path('delete_logout_time/<int:pk>', views.delete_logout_time.as_view(), name='delete_logout_time'),

path('delete_pickup/<int:pk>', views.delete_pickup.as_view(), name='delete_pickup'),

path('delete_drop/<int:pk>', views.delete_drop.as_view(), name='delete_drop'),

path('Add_pickup/', views.Add_pickup.as_view(), name='Add_pickup'),

path('Add_drop/', views.Add_drop.as_view(), name='Add_drop'),

path('Add_login/', views.Add_login.as_view(), name='Add_login'),

path('Add_logout/', views.Add_logout.as_view(), name='Add_logout'),

path('Add_new_user/', views.Add_new_user.as_view(), name='Add_new_user'),

path('update_user/<int:pk>', views.update_user.as_view(), name='update_user'),

path('delete_user/<int:pk>', views.delete_user.as_view(), name='delete_user'),












]

marketing_tool_lead_manager_app/models.py
#<---------Django Imported Libraries--------->
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.utils import timezone
#</---------Django Imported Libraries--------->

# Create your models here.

#user Model
class CustomUser(AbstractUser):
    '''Overrides the custom django user model'''
    # Datafields
    NORMAL_USER = 1
    RESTAURANT_1_ADMIN = 2
    SUPER_ADMIN = 13
    ROLE_CHOICES = (
      (NORMAL_USER,'normal_user'),
      (RESTAURANT_1_ADMIN,'admin'),
      (SUPER_ADMIN,'super_admin'),
    )
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES,default=NORMAL_USER)
    name = models.CharField(max_length=264, blank='True')
    password_change_request = models.BooleanField(default=False)

#Pickup location Model
class Pickup_Location(models.Model):
    Location_Name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.Location_Name)

#Drop location Model
class Drop_Location(models.Model):
    Drop_Name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.Drop_Name)

#Login Time Model
class Login_Time(models.Model):
    Time = models.CharField(max_length=200)

    def __str__(self):
        return str(self.Time)

#Logout Time Model
class Logout_Time(models.Model):
    Time = models.CharField(max_length=200)

    def __str__(self):
        return str(self.Time)

#Leads Model
class Leads(models.Model):
    LEAD_STATUS = (('Interested','Interested'),
                   ('Undecided','Undecided'),
                   ('Uncontacted','Uncontacted'),
                   ('Converted','Converted'))
    Created_at = models.DateTimeField(auto_now_add=True)
    Updated_at = models.DateTimeField(auto_now=True)
    City = models.CharField(max_length=264,blank=True)
    Name = models.CharField(max_length=264)
    Gender	=	models.CharField(max_length=264,blank=True)
    EmailId	=	models.CharField(max_length=264,blank=True)
    ContactNo	=	models.CharField(max_length=264,blank=True)
    CompanyName	=	models.CharField(max_length=264,blank=True)
    TravalToWork	=	models.CharField(max_length=264,blank=True)
    TravelToWorkOther	= models.CharField(max_length=264,blank=True)
    MonthlySpend	=	models.CharField(max_length=264,blank=True)
    HearAboutUs	=	models.CharField(max_length=264,blank=True)
    SubmittedOn	=	models.CharField(max_length=264,blank=True)
    Lead_Status = models.CharField(choices=LEAD_STATUS,max_length=264,default="Uncontacted")
    Remark = models.TextField(blank=True)
    LocationFromOther = models.CharField(max_length=264,blank=True)
    SubmittedOnDate	=	models.DateTimeField(default=timezone.now)
    is_valid = models.BooleanField(default=False)
    Pickup_Location_id = models.ForeignKey(Pickup_Location, on_delete = models.CASCADE)
    Drop_Location_id = models.ForeignKey(Drop_Location,  on_delete = models.CASCADE)
    Login_Time_id = models.ForeignKey(Login_Time, on_delete = models.CASCADE,related_name = 'pickup_location')
    Logout_Time_id = models.ForeignKey(Logout_Time,  on_delete = models.CASCADE)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name_plural = "Leads Collected"
        verbose_name = "Lead"

class Lead_Comment(models.Model):
    status_type_choices=(('Interested','Interested'),
                        ('Undecided','Undecided'),
                        ('Uncontacted','Uncontacted'),
                        ('Converted','Converted'))
    product_interested_in_type_choice=(('Nodal Service','Nodal Service'),
                                      ('Hub Cab','Hub Cab'),
                                      ('Others','Others'))
    lead_comment_id=models.ForeignKey(Leads, on_delete = models.CASCADE)
    lead_comment_updated_by =models.ForeignKey(CustomUser,on_delete= models.CASCADE)
    lead_comment_name=models.CharField(choices=status_type_choices,max_length=264)
    lead_comment_create_date= models.DateTimeField(default=timezone.now)
    lead_comment_remark=models.TextField(max_length=264,blank=True)
    lead_comment_product_interested_in = models.CharField(choices=product_interested_in_type_choice,max_length=264,default='Not Selected')
    lead_comment_next_followup_date=models.DateField(max_length=264)
    lead_comment_updated = models.DateTimeField(auto_now=True)
    lead_comment_Created_at = models.DateTimeField(auto_now_add=True)
    lead_comment_Updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name_plural = "Leads Comment"
        verbose_name = "Lead Comment"


class Company_Leads(models.Model):
    company_leads_added_by = models.ForeignKey(CustomUser,on_delete= models.CASCADE)
    company_leads_pickup_location_id = models.ForeignKey(Pickup_Location, on_delete = models.CASCADE)
    company_leads_created_at = models.DateTimeField(auto_now_add=True)
    company_leads_corporate_hub =models.CharField(max_length=264)
    company_leads_company_name = models.CharField(max_length=264)
    company_leads_login_time =models.ForeignKey(Login_Time,on_delete= models.CASCADE)
    company_leads_logout_time=models.ForeignKey(Logout_Time,on_delete= models.CASCADE)
    company_leads_employee_strength= models.CharField(max_length=264)
    company_leads_contact_person=models.CharField(max_length=264)
    company_leads_designation=models.CharField(max_length=264,default='')
    company_leads_contact_mobile=models.CharField(max_length=264)
    company_leads_contact_email= models.CharField(max_length=264)
    
    def __str__(self):
        return str(self.pk)

class Company_Leads_Comment(models.Model):
	status_type_choices=(('Interested','Interested'),
                            ('Undecided','Undecided'),
                            ('Uncontacted','Uncontacted'),
                            ('Converted','Converted'))
	product_interested_in_type_choice=(('Nodel Service','Nodel Service'),
                                      ('Hub Cab','Hub Cab'),
                                      ('Others','Others'))
	company_lead_comment_id=models.ForeignKey(Company_Leads, on_delete = models.CASCADE)
	company_lead_comment_updated_by =models.ForeignKey(CustomUser,on_delete= models.CASCADE)
	company_lead_comment_name=models.CharField(choices=status_type_choices,max_length=264)
	company_lead_comment_create_date= models.DateTimeField(default=timezone.now)
	company_lead_comment_remark=models.TextField(max_length=264,blank=True)

	def __str__(self):
		return str(self.pk)

marketing_tool_lead_manager_app/forms.py
from .models import Leads,Pickup_Location,Drop_Location,Lead_Comment,Login_Time,Logout_Time,CustomUser
from bootstrap_modal_forms.mixins import PopRequestMixin,CreateUpdateAjaxMixin
from bootstrap_modal_forms.forms import BSModalForm
from django.contrib.auth.forms import UserCreationForm


class CustomUserForm(PopRequestMixin, CreateUpdateAjaxMixin,
                             UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'role','email', 'password1', 'password2')

class CustomUserUpdateForm(BSModalForm):
    class Meta:
        model = CustomUser
        fields = ['username','email']         

class LeadForm(BSModalForm):

    class Meta:
        model = Leads
        fields = ['Lead_Status','Pickup_Location_id','Drop_Location_id','Login_Time_id','Logout_Time_id','Remark',]

class UpdateLocationFrom(BSModalForm):
    class Meta:
        model = Pickup_Location
        fields = ('Location_Name',)

class UpdateLocationTo(BSModalForm):
    class Meta:
        model = Drop_Location
        fields = ['Drop_Name']

class LeadCommentForm(BSModalForm):
    class Meta:
        model = Lead_Comment
        fields = ['lead_comment_name','lead_comment_remark','lead_comment_product_interested_in','lead_comment_next_followup_date']

class Login_Time_form(BSModalForm):
    class Meta:
        model = Login_Time
        fields = ['Time']

class Logout_Time_form(BSModalForm):
    class Meta:
        model = Logout_Time
        fields = ['Time']


marketing_tool_lead_manager_app/templates/marketing_tool_lead_manager_app/Update_Login_Time.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Login Time</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Update</button>
  </div>

</form>

marketing_tool_lead_manager_app/templates/marketing_tool_lead_manager_app/base_b2b.html
<!DOCTYPE html>
<html>
{% load static %}
<head>

    <title>Marketing Tool</title>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
     <!-- jQuery Custom Scroller CDN -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'marketing_tool_lead_manager_app/css/bootstrap.min.css' %}" />

    <link rel="stylesheet" type="text/css" href="{% static 'marketing_tool_lead_manager_app/DataTables/datatables.min.css' %}" />
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     
    <script type="text/javascript" src="{% static 'marketing_tool_lead_manager_app/DataTables/datatables.min.js' %}"></script>
   
    {% block stylesheets %}
   {% endblock stylesheets %}
    {% block headscript %}
   {% endblock headscript %}
    <style>
        hr {
            background-color: black;
        }
    </style>
    <style>
        #colmn {
            width: 1000px;
        }
 
        thead input {
            width: 100%;
        }
    </style>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #1f5b99">
        <a class="navbar-brand" href="#" style="color: #ffffff;font-weight: bold">MARKETING TOOL</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'marketing_tool_lead_manager_app:company_lead_form' %}" style="color: #ffffff"> Leads Form</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'marketing_tool_lead_manager_app:company_lead_data' %}" style="color: #ffffff"> Leads Data</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'marketing_tool_lead_manager_app:company_lead_report' %}" style="color: #ffffff"> Leads Report</a>
                </li>
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0" action="{% url 'marketing_tool_lead_manager_app:lead_zing_grid_list' %}">
                  <a href="#"><button class="btn btn-success my-2 my-sm-0" style="margin-left:10px">Switch B2C</button></a>
                     </form>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <button class="btn btn-success my-2 my-sm-0" type="submit">Logout</button>
            </form>
        </div>
    </nav><br><br><br>
    {% block content %}
   {% endblock %}

   {% block script %}
   {% endblock %}
    
   {% block extrascript %}
   {% endblock %}
    </body>
</html>

marketing_tool_lead_manager_app/templates/marketing_tool_lead_manager_app/deletelead.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Lead</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>Are you sure you want to delete Lead with title
      <strong>{{ Lead.title }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>

</form>

marketing_tool_lead_manager_app/templates/marketing_tool_lead_manager_app/location_to.html
{% extends 'marketing_tool_lead_manager_app/base.html' %}
{% load pickup_location_filter %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}

{% block content %}
<!-- Modal for CURD Operation -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
     <!-- PAGE CONTENT  -->

<div>
    <h4>Location To<span style="float: right"><button class="signup-btn btn btn-info" type="button" name="button">Click here to Add Location</button></span></h4>
    
    <hr>
    <table id="myTable" class="display" style="width: 100%">
        <thead>
            <tr>
                <th>Location From ID</th>
                <th>Location From Name</th>
                <th>Change Name</th>
                <th>Delete Location</th>
            </tr>
            <tr>
                <th>Location From ID</th>
                <th>Location From Name</th>
                <th><center>Change Name</center></th>
                <th><center>Delete Location</center></th>
            </tr>
        </thead>
        <tbody>
            {% for location in location_to %}
            <tr>
                <td>{{location.pk}}</td>
                <td>{{location.Drop_Name}}</td>
                <td><center> <button type="button" class="update-location btn btn-sm btn-primary" data-id="{% url 'marketing_tool_lead_manager_app:update_location' pk=location.pk  %}">
                                <span class="fa fa-edit"></span>
                            </button></center></td>
                <td><center><button class="delete-location btn btn-sm btn-danger" data-id="{% url 'marketing_tool_lead_manager_app:delete_drop' location.pk %}">
                <span class="fa fa-trash"></span></button></center></td>            
            </tr>
            {% endfor %}
        </tbody>
        {% comment %} <tfoot>
            <tr>
                <th>Location From ID</th>
                <th>Location From Name</th>
                <th>Change Name</th>
            </tr>
        </tfoot> {% endcomment %}
    </table>
</div>
{% endblock %}

<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
{% block script %}

{% endblock %}
{% block extrascript %}
<script>
	$(document).ready(function() {
		$('#myTable').DataTable({
			orderCellsTop: true,
			fixedHeader: true,
			"lengthMenu": [
				[-1],
				["All"]
			],
			initComplete: function() {
				this.api().columns().every(function() {
					var column = this;
					var select = $('<select><option value=""></option></select>')
						.appendTo($(column.header()).empty())
						.on('change', function() {
							var val = $.fn.dataTable.util.escapeRegex(
								$(this).val()
							);

							column
								.search(val ? '^' + val + '$' : '', true, false)
								.draw();
						});

					column.data().unique().sort().each(function(d, j) {
						select.append('<option value="' + d + '">' + d + '</option>')
					});
				});
			}
		});
	});

</script>
<script type="text/javascript">
    $(function() {
        $(".signup-btn").modalForm({formURL: "{% url 'marketing_tool_lead_manager_app:Add_drop' %}"});
        $(".update-location").each(function() {
            $(this).modalForm({
                formURL: $(this).data('id')
            });
        });
        $(".delete-location").each(function() {
            $(this).modalForm({
                formURL: $(this).data('id')
            });
        });
        $(".read-location").each(function() {
            $(this).modalForm({
                formURL: $(this).data('id')
            });
        });
    });
</script>
{% endblock %}

marketing_tool_lead_manager_app/templates/marketing_tool_lead_manager_app/update.html
examples/update.html

...
{% include hot_template %}
...